### Project specific config ###
language: ruby

matrix:
  include:
    - os: linux
      rvm: 2.3.1
      env: ATOM_CHANNEL=stable

    - os: linux
      rvm: 2.3.1
      env: ATOM_CHANNEL=beta

install:
  - gem install scss_lint

before_script:
  - scss-lint --version

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

dist: trusty

addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev
